<a href="https://colab.research.google.com/github/MiguelRoiNava/Miguel-Nava/blob/main/Coding_activity_3_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3x3 inverse

In [3]:
#Matrix A = ([[7,2,2],[6,-3,6],[3,9,6]])
import numpy as np
A = np.array([[7,2,2],[6,-3,6],[3,9,6]])
print(A)
B = np.linalg.inv(A)
print(B)

[[ 7  2  2]
 [ 6 -3  6]
 [ 3  9  6]]
[[ 0.17391304 -0.01449275 -0.04347826]
 [ 0.04347826 -0.08695652  0.07246377]
 [-0.15217391  0.13768116  0.07971014]]


3x3 transpose

In [6]:
A = np.array([[7,2,2],[6,-3,6],[3,9,6]])
print(A)
B = np.transpose(A)
print(B)

[[ 7  2  2]
 [ 6 -3  6]
 [ 3  9  6]]
[[ 7  6  3]
 [ 2 -3  9]
 [ 2  6  6]]


4x4 inverse

In [5]:
#Matrix A = ([[7,2,2,4],[6,-3,6,-3],[3,9,6,6],[-1,9,5,2]])
import numpy as np
A = np.array([[7,2,2,4],[6,-3,6,-3],[3,9,6,6],[-1,9,5,2]])
print(A)
B = np.linalg.inv(A)
print(B)

[[ 7  2  2  4]
 [ 6 -3  6 -3]
 [ 3  9  6  6]
 [-1  9  5  2]]
[[ 2.72727273e-01  1.98254112e-17 -2.42424242e-01  1.81818182e-01]
 [ 2.23140496e-01 -6.06060606e-02 -2.89256198e-01  3.30578512e-01]
 [-2.64462810e-01  1.21212121e-01  3.05785124e-01 -2.06611570e-01]
 [-2.06611570e-01 -3.03030303e-02  4.15977961e-01 -3.80165289e-01]]


4x4 transpose

In [7]:
A = np.array([[7,2,2,4],[6,-3,6,-3],[3,9,6,6],[-1,9,5,2]])
print(A)
B = np.transpose(A)
print(B)

[[ 7  2  2  4]
 [ 6 -3  6 -3]
 [ 3  9  6  6]
 [-1  9  5  2]]
[[ 7  6  3 -1]
 [ 2 -3  9  9]
 [ 2  6  6  5]
 [ 4 -3  6  2]]
