<a href="https://colab.research.google.com/github/MiguelRoiNava/Miguel-Nava/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[4,10,8],[10,26,26],[8,26,26]])
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)
B = np.array([[44],[128],[214]])
print(B )
X = np.dot(inv_A,B)
print(X)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 26]]
[[ 0.          0.5        -0.5       ]
 [ 0.5        -0.38461538  0.23076923]
 [-0.5         0.23076923 -0.03846154]]
[[ 44]
 [128]
 [214]]
[[-43.        ]
 [ 22.15384615]
 [ -0.69230769]]
